### ISSUE TITLE
Ansible Failure: ESCU REST API Installation Failure

### ISSUE THREAD

**Issue by lstmfx** [splunk/attack_range#141]
Just pulled down the latest from attack_range and attempt to run a generic build using the build action and got stopped on ECSU app installation through the REST API since there was a connection refused for the splunk instanced installed on the VM. I enabled boot-on-start for splunk and restart through the ansible roles but that didn't seem to resolve the installation issue 😅.
Any suggestions for a fix?
Thanks!
[debug.log](https://github.com/splunk/attack_range/files/3969690/debug.log)

**Comment by d1vious** [comment]
@lstmfx my first suggestion would be to increate the timeout here https://github.com/splunk/attack_range/blob/develop/ansible/roles/search_head/tasks/install_escu_app.yml#L23 to maybe 300 and try it again. Although the error says connection refuse instead of timeout. Alternative, I would attempt doing the local POST request via curl yourself and see the response from that. To do this:
1. log into the splunk vagrant box: `cd attack_range/vagrant` then run `vagrant ssh splunk-server`
2. from here make sure that Ansible indeed downloaded the latest ESCU package from s3, run 
```
vagrant@splunk-server:~$ ls -lah /tmp/escu_app.tgz
-rw-r--r-- 1 root root 4.2M Dec 16 13:33 /tmp/escu_app.tgz
```
3. if is there run the following curl command and paste back the output here
```
curl -k -XPOST -H 'Content-Type: "application/x-www-form-urlencoded' -u admin:changeme https://127.0.0.1:8089/services/apps/local -d "name=/tmp/escu_app.tgz&update=true&filename=true"
```
assuming you did not change the default splunk admin password in https://github.com/splunk/attack_range/blob/develop/attack_range.conf#L12 otherwise just update the command to reflect your password.

**Comment by lstmfx** [comment]
Turned out to be a resource and timeout issue 😅.  I upped the timeout and it got the app to install. Thanks for the support! :)
