### ISSUE TITLE
All apps should "maybe" global permisions

### ISSUE THREAD

**Issue by patel-bhavin** [splunk/attack_range#151]
for attack_range to work with ESCU, ASX and all other apps. we should perhaps have all apps to have global permissions since we .conf file configurations from various Splunk apps

**Comment by P4T12ICK** [comment]
I'm working on that. The branch search_command contains it that the role admin contains all the indexes as default indexes.

**Comment by P4T12ICK** [comment]
Hello, can you be a little bit more specific. I think most of the configurations in the apps ESCU, ASX have already global permission. Based on feedback, I changed that all indexes are added as default indexes. I'm not sure if we should implement these changes into ESCU or ASX, instead of Attack Range. Let me know your opinion.

**Comment by P4T12ICK** [comment]
I think this needs to be fixed in the apps and not in the Attack Range.
