### ISSUE TITLE
Bug with simulates on vagrant mode

### ISSUE THREAD

**Issue by d1vious** [splunk/attack_range#301]
Reported by Shannon Davis:
Have a customer trying to launch a couple of attack-range tests but hitting this.  Haven’t troubleshooted much yet just in case this is an easy fix
```
TASK [atomic_red_team : Install Atomic Red Team] *******************************
fatal: [10.0.1.14]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'art_repository' is undefined\n\nThe error appears to be in '/Users/jeremymason/Projects/attack_range/ansible/roles/atomic_red_team/tasks/main.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Atomic Red Team\n  ^ here\n"}
10.0.1.14                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
PLAY RECAP *********************************************************************
10.0.1.14                  : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
2020-07-14 15:56:06,042 - ERROR - attack_range - failed to executed technique ID T1117,T1003 against target: attack-range-windows-domain-controller

```

**Comment by jez-github** [comment]
When trying to run the Atomic Red simulations with #301 it fails to find "Invoke-AtomicRedTeam.psd1" in the Atomic folder:

TASK [atomic_red_team : Get requirements for Atomic Red Team Technique] ********
l.Commands.ImportModuleCommand\r\n \r\nInvoke-AtomicTest : The term 'Invoke-AtomicTest' is not recognized as the name of a cmdlet, function, script file, or \r\noperable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try \r\nagain.\r\nAt line:2 char:1\r\n+ Invoke-AtomicTest \"T1117\" -GetPrereqs\r\n+ ~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (Invoke-AtomicTest:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException", "stderr_lines": ["Import-Module : The specified module 'C:\\AtomicRedTeam\\invoke-atomicredteam\\Invoke-AtomicRedTeam.psd1' was not loaded ", "because no valid module file was found in any module directory.", "At line:1 char:65", "+ ... ing $false; Import-Module \"C:\\AtomicRedTeam\\invoke-atomicredteam\\Invo ...", "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : ResourceUnavailable: (C:\\AtomicRedTea...micRedTeam.psdfatal: [10.0.1.15]: FAILED! => {"changed": true, "cmd": "Import-Module \"C:\\AtomicRedTeam\\invoke-atomicredteam\\Invoke-AtomicRedTeam.psd1\" -Force\nInvoke-AtomicTest \"T1117\" -GetPrereqs", "delta": "0:00:01.000267", "end": "2020-07-15 05:33:41.809422", "msg": "non-zero return code", "rc": 1, "start": "2020-07-15 05:33:40.809154", "stderr": "Import-Module : The specified module 'C:\\AtomicRedTeam\\invoke-atomicredteam\\Invoke-AtomicRedTeam.psd1' was not loaded \r\nbecause no valid module file was found in any module directory.\r\nAt line:1 char:65\r\n+ ... ing $false; Import-Module \"C:\\AtomicRedTeam\\invoke-atomicredteam\\Invo ...\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ResourceUnavailable: (C:\\AtomicRedTea...micRedTeam.psd1:String) [Import-Module], FileNot \r\n   FoundException\r\n    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand\r\n \r\nInvoke-AtomicTest : The term 'Invoke-AtomicTest' is not recognized as the name of a cmdlet, function, script file, or \r\noperable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try \r\nagain.\r\nAt line:2 char:1\r\n+ Invoke-AtomicTest \"T1117\" -GetPrereqs\r\n+ ~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (Invoke-AtomicTest:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException", "stderr_lines": ["Import-Module : The specified module 'C:\\AtomicRedTeam\\invoke-atomicredteam\\Invoke-AtomicRedTeam.psd1' was not loaded ", "because no valid module file was found in any module directory.", "At line:1 char:65", "+ ... ing $false; Import-Module \"C:\\AtomicRedTeam\\invoke-atomicredteam\\Invo ...", "+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : ResourceUnavailable: (C:\\AtomicRedTea...micRedTeam.psd1:String) [Import-Module], FileNot ", "   FoundException", "    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand", " ", "Invoke-AtomicTest : The term 'Invoke-AtomicTest' is not recognized as the name of a cmdlet, function, script file, or ", "operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try ", "again.", "At line:2 char:1", "+ Invoke-AtomicTest \"T1117\" -GetPrereqs", "+ ~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : ObjectNotFound: (Invoke-AtomicTest:String) [], CommandNotFoundException", "    + FullyQualifiedErrorId : CommandNotFoundException"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
10.0.1.15                  : ok=7    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

2020-07-15 15:33:41,962 - ERROR - attack_range - failed to executed technique ID T1117,T1003 against target: attack-range-windows-server

**Comment by d1vious** [comment]
@jez-github I believe this was solved in a more recent PR related to the default atomic red team branch we use. Please give it a try again!

**Comment by d1vious** [comment]
We removed vagrant from the project it is now part of the local attack_range FYI: https://github.com/splunk/attack_range_local/
