### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by WOOOOONG** [splunk/attack_range#681]
Hello. I am a Yeungnam University College student in South korea. So my English is not good.
I am studying BAS(Breach and Attack Simulation) for to use my graduation project.
I want to make BAS like attack_range or use attack_range.

My attack server(ip: 192.168.13.1) do simulate attack(ex; T1003) to victim server(ip: 192.168.130.1) in another server.

1. How can I use attack_range? or Does attack range not support attack another server except AWS, AZURE?
2. If attack range do not support, I want to make attack paylaod for attakck another server using atomic red team opensource. But I don't know how to use atomic red team opensource to using in network not local. Can you give me some advice?

Thank you,
Jeongwoong Yoon(woong3164@naver.com)

**Comment by P4T12ICK** [comment]
Hello, the Attack Range builds the complete infrastructure in AWS, Azure or local with Virtualbox. 
In Attack Range, we use Atomic Red Team and Prelude to only attack the Attack Range infrastructure and not outside of Attack Range. 
In order to run Atomic Red Team remote, you can use the project Invoke Atomic Red Team. Here is a wiki article describes how to execute an atomic on a remote system:
https://github.com/redcanaryco/invoke-atomicredteam/wiki/Execute-Atomic-Tests-(Remote)

**Comment by WOOOOONG** [comment]
Thank you for your kindness.
