### ISSUE TITLE
Build error on local Linux installation

### ISSUE THREAD

**Issue by TofBaasken** [splunk/attack_range#883]
Hi , 
I'm following your guidelines step for step from https://attack-range.readthedocs.io/en/latest/Attack_Range_AWS.html#linux on a fresh Ubuntu 22.04.3 LTS machine.
When trying to perform python attack_range.py build on the machine I get : 

2024-02-20 11:20:19,112 - INFO - attack_range - [action] > build

Bringing machine 'ar-splunk-attack-range-key-pair-ar' up with 'virtualbox' provider...
Bringing machine 'ar-win-attack-range-key-pair-ar-0' up with 'virtualbox' provider...
==> ar-splunk-attack-range-key-pair-ar: Checking if box 'generic/ubuntu2004' version '4.3.12' is up to date...
==> ar-splunk-attack-range-key-pair-ar: Clearing any previously set forwarded ports...
==> ar-splunk-attack-range-key-pair-ar: Clearing any previously set network interfaces...
==> ar-splunk-attack-range-key-pair-ar: Preparing network interfaces based on configuration...
    ar-splunk-attack-range-key-pair-ar: Adapter 1: nat
    ar-splunk-attack-range-key-pair-ar: Adapter 2: hostonly
==> ar-splunk-attack-range-key-pair-ar: Forwarding ports...
    ar-splunk-attack-range-key-pair-ar: 8000 (guest) => 8000 (host) (adapter 1)
    ar-splunk-attack-range-key-pair-ar: 8089 (guest) => 8089 (host) (adapter 1)
    ar-splunk-attack-range-key-pair-ar: 8080 (guest) => 8080 (host) (adapter 1)
    ar-splunk-attack-range-key-pair-ar: 22 (guest) => 2222 (host) (adapter 1)
==> ar-splunk-attack-range-key-pair-ar: Running 'pre-boot' VM customizations...
==> ar-splunk-attack-range-key-pair-ar: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "2f457d3e-1e25-4514-95dc-ad903a3efe34", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'ar-splunk' has terminated unexpectedly during startup because of signal 6
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Any idea ? I tried on 2 fresh , different ubuntu machines  , resulting in the same issue ....

**Comment by kyusan93** [comment]
Run this with Ubuntu Desktop edition with GUI.
Or install KDE if you are using Ubuntu Server edition without any GUI
Else you can edit the vagrant files vb.gui to false.

**Comment by tkhr788** [comment]
I too have had this error.
So, as advised, I changed vb.gui=true to vb.gui=false in the vagrant files and the installation proceeded.
However, it stopped with the following error.

==> ar-win-attack-range-key-pair-ar-0: Waiting for machine to boot. This may take a few minutes...
    ar-win-attack-range-key-pair-ar-0: WinRM address: 127.0.0.1:5985
    ar-win-attack-range-key-pair-ar-0: WinRM username: vagrant
    ar-win-attack-range-key-pair-ar-0: WinRM execution_time_limit: PT2H
    ar-win-attack-range-key-pair-ar-0: WinRM transport: plaintext
**The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.**


Is there a solution to this problem?

**Comment by P4T12ICK** [comment]
You need to check your vagrant and Virtual Box configurations. We have many users using the Attack Range local successfully with this configuration.
