### ISSUE TITLE
Concern about Windows Licenses

### ISSUE THREAD

**Issue by Chaves2021** [splunk/attack_range#897]
Hii guys, I'm using the local version of attack_range for an university project, and I've got questioned about the legality of using Windows machines without activation key.
I didn't know how to answer that question, and thats why I'm asking you.

Thanks :)

**Comment by 0xtamsee1** [comment]
What was their question anyway ? because I'm really curious to know why they have a concern about "activation" of windows when they could have had a bigger concern of "adversary simulation".

Anyway, attack_range is a research project so you can argue that activation of windows should not be a priority as this is not commercialized project. Also Microsoft provides [Windows](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) development environment for evaluation which is also a "not activated" virtual machine.
